### ISSUE TITLE
Possible improvement

### ISSUE THREAD

**Issue by kujtimiihoxha** [sensedeep/dynamodb-onetable#179]
I just wanted to share that for a personal project I implemented a way to use `decorators` to specify the schema instead of a separate schema configuration.

If you see value in this I can find time to migrate it and make it available through `dynamodb-onetable` and open source it.

The definitions look like this 

```js
@Entity({
  name: 'user',
  indexes: {
    primary: {
      hash: '${_type}:${id}',
      sort: '${_type}:',
    },
  },
})
export class UserOrmEntity extends OrmEntityBase {
  @Attribute()
  name: string;
  @Attribute()
  username: string;
  @Attribute()
  avatarUrl: string;
  @Attribute()
  email: string;
  @Attribute({
    isEnum: true,
  })
  status: UserStatus;
  @Attribute()
  flags?: Set<UserFlag>;
}
```

You need to configure the table with a config that looks like this

```js
 const tableConfig: TableConfigurations = {
  name: process.env.USERS_TABLE_NAME as string,
  schema: {
    primary: {
      hash: 'PK',
      sort: 'SK',
      description: 'Primary table index',
    },
    indexes: {
      GSI1: {
        name: 'GSI1',
        hash: 'PK1',
        sort: 'SK1',
        description: 'Some description '
        },
    },
    version: '0.0.1',
  },
};
```
And create the table like this

```js
  const table = new Table({
    ...props,
    schema: {
      name: tableConfig.schema.name,
      version: tableConfig.schema.version,
      format: tableConfig.schema.format,
      params: tableConfig.schema.params,
      indexes: {
        primary: tableConfig.schema.primary,
        ...tableConfig.schema.indexes,
      },
      models: generateSchemaFromTableConfig(tableConfig,[UserOrmEntity]),
    },
  });
```

`generateSchemaFromTableConfig` is a function that does all the magic behind the scenes.

This is working pretty well for me.

**Comment by kujtimiihoxha** [comment]
`@Attribute` accepts all the config of `OneFieldSchema` with some small modifications for `enum`

**Comment by mobsense** [comment]
That actually sounds like it would be a really good separate NPM / repo. People who need it could install atop OneTable.

OneTable needs to support 100% declarative schemas and a separation of code and schema. The reason is we want tables to be self-describing and to have the schema stored in the table itself. This means there must be a literal schema and it could be confusing to be advocating both a literal schema and an inline decorator based approach.

I think there are definitely folks for whom the decorator approach is attractive, but it would be cleaner as a separate repo / project. We could link to it to people know it is available.

See #173

**Comment by kujtimiihoxha** [comment]
That makes total sense. I will see if I find some time to create a library for this.

One note here is that 

```
generateSchemaFromTableConfig(tableConfig,[UserOrmEntity]),
```

Will actually generate the schema in the end 😄 

I will close this for now.

**Comment by mobsense** [comment]
That is pretty cool. We originally went down that path, but settled on TS bindings directly from the schema. 

But I know the @directive approach appeals to many.
