### ISSUE TITLE
Built in UUID function does not generate real UUIDs

### ISSUE THREAD

**Issue by rjmackay** [sensedeep/dynamodb-onetable#191]
**Describe the bug**
The built in UUID function just generates a random string. It's not a UUID, and doesn't comply with the spec.

**Expected behavior**
It should be a real UUID, or be renamed to just `randomId` 

**Screenshots**

**Environment (please complete the following information):**
 - OS
 - Node Version
 - OneTable Version

**Additional context**

**Comment by mobsense** [comment]
Fair comment. We want zero dependencies with the library, so we don't use the uuidv4 libraries. However, the algorithm could certainly be updated to be uuid compliant.

**Comment by mobsense** [comment]
Here is a patch:

```
diff --git a/src/UUID.js b/src/UUID.js
index 25d5cdd..e7678bf 100644
--- a/src/UUID.js
+++ b/src/UUID.js
@@ -4,7 +4,7 @@
     Consider ULIDs which are crypto sortable.
 */
 export default function UUID() {
-    return 'xxxxxxxxxxxxxxxxyxxxxxxxxxyxxxxx'.replace(/[xy]/g, function(c) {
+    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
         let r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8)
         return v.toString(16)
     })
```

**Comment by trustthe27** [comment]
Hi @mobsense, I would consider this behaviour a breaking change in the 2.1.1 release.
Because everyone who used uuids with the matching validation from your docs before (`uuid: /^[0-9A-F]{32}$/i,`), will now get a validation error on creating new items, as you also added hyphens to it (see c949aa3c2fd591d6a1be29d6ec75c72284897fde and bd67bb4b7ceaaac4fbf85c3fe1217a35ab90578d).

**Comment by mobsense** [comment]
Unfortunately a bit of a catch 22. Earlier versions were UUID standard compliant and more recently were not.

Agree, probably should have been a 2.2 with a warning. I'll update the release notes.

The impact is only to your validation code. The old and new format UUIDs are valid.

FYI: validations on the UUID a probably not as high priority as user generated data as they are an internally generated parameter.

**Comment by trustthe27** [comment]
Thanks for considering this. After updating to 2.1.1 I had the problem by myself. Suddenly a create was not working anymore. After updating the validation regex it worked again, of course.

**Comment by rjmackay** [comment]
@mobsense I'm pretty sure that's still not actually spec compliant since you're setting the version number but not the `clock_seq_hi_and_reserved`

> The algorithm is as follows:
> 
>    o  Set the two most significant bits (bits 6 and 7) of the
>       clock_seq_hi_and_reserved to zero and one, respectively.
> 
>    o  Set the four most significant bits (bits 12 through 15) of the
>       time_hi_and_version field to the 4-bit version number from
>       Section 4.1.3.
> 
>    o  Set all the other bits to randomly (or pseudo-randomly) chosen
>       values.
Ref: https://www.ietf.org/rfc/rfc4122.txt

You can also see this here: https://github.com/uuidjs/uuid/blob/main/src/v4.js#L10

Personally, I'd suggest you don't bundle a UUID implementation at all, and rather used `uuid` as optional dependency, but obviously that won't work for everyone.

**Comment by mobsense** [comment]
The design was to have a very simple, small UUID and to favor the ULID which is ordered and crypto grade. We have to have a UUID function to call, so we can't make it an optional dependency as that would make setup more complex for everyone.

You can currently provide your own UUID by setting the Table params.uuid to a function of your choosing. So you can import uuidv4 NPM and use that.

I'm happy to have the uuid implementation upgraded as you outlined, but got a few higher priorities ahead of that in the queue. Would definitely accept a PR to do that.

**Comment by KennyDizi** [comment]
how about KSUID?

**Comment by mobsense** [comment]
You can add your own ksuid via the table constructor by setting the params.uuid to a function of your choosing.

**Comment by adrian-grajdeanu** [comment]
But Table.setMakeID is not declared in Table in Table.d.ts :(

**Comment by mobsense** [comment]
Quick comment clarifying my thoughts on this.

I agree with the sentiments put by @adrian-grajdeanu and @rjmackay.  The best solution would be for ULID to be the default and for UUID to be removed. Users can then use the NPM uuidv4 if they wish via Table.setMakeID.

So there are 2 issues:

* Removing UUID
* Changing the default to ULID

The reason I've been slow to act on this is backward compatibility. Unfortunately, the Table params 'uuid' was defaulted to a the internal UUID. If you use uuid: true in the schema, you get a UUID by default. So switching the default to ULID will be a breaking change. There is no way round that. If people are using validations on their UUID fields, they will break if we change the default AND they have not explicitly set uuid="uuid" and supplied their own via setMakeID.

If a user has used uuid: true and not set any Table UUID/ULID defaults, then this will be a breaking change.

We can use a SemVer minor version number change to signify, but some users don't really track SemVer meaning closely.

So this issue probably needs to wait the the next bigger upgrade.

**Comment by mobsense** [comment]
One more associated issue.

The schema field uuid property should then be simply true or false and not be 'uuid' or 'ulid'.
If users have other custom ID needs, they can simply define the property value on create().

The set of changes would then be:

* A makeID function can be defined via the Table params.uuid or via Table.setMakeID.
* The default makeID is ULID.
* The schema uuid property would then be true or false and the defined make ID function is called.

Last issue is that the use of `uuid` as a name is then misleading. It probably should be deprecated, supported in transition and be renamed to something else like `generate`. Thoughts?

**Comment by adrian-grajdeanu** [comment]
I like the direction where this issue is evolving. Simplification where is possible, never hurts!

Now, if you're going to rename _uuid_ property to something like _generate_, let's consider the existence of _setMakeID_ and bring them all in sync. _makeID_ or _generateID_ are good choices. Personally I'd rather name them _makeIdFn_ or _generateIdFn_ to clearly tell anyone these are functions, but this may be a bigger stylistic change.

Jan 6, 2022 18:08:45 mobsense ***@***.***>:

> One more associated issue.
> 
> The schema field uuid property should then be simply true or false and not be 'uuid' or 'ulid'.
> If users have other custom ID needs, they can simply define the property value on create().
> 
> The set of changes would then be:
> 
* > A makeID function can be defined via the Table params.uuid or via Table.setMakeID.
* > The default makeID is ULID.
* > The schema uuid property would then be true or false and the defined make ID function is called.

**Comment by mobsense** [comment]
AHHH, we're thinking the same way.

I just prototyped renaming schema uuid => generate. Works much better. AND setGenerate instead of setMakeID. 

You can set a generator via setGenerator or via Table params.generator == function. 

Under the hood, we can issue deprecation messages about using "uuid" but support that.

The prototype looks much better.

**Comment by mobsense** [comment]
The plan is to rename to 'generate' and issue deprecation warnings in the next release.

We will keep the UUID routine so it can be used in the browser without requiring node crypto. The doc will clearly say it is not UUID v4 compliant. We'll remove the default to uuid in the release after that. You need to be explicit and use generate: "ulid" or "uuid" in your schema.  Custom generators are defined via Table constructor and then use generate: true in the schema.

**Comment by mobsense** [comment]
I'm going to mark this as closed, despite not fixing the "title" issue. Please complain if you still feel strongly about this.

The reason is that we're removing it from being the default, we're making it explicit to select "ulid" vs "uuid". But most important, we can't get a crypto grade version in the browser. So we need the current version.
