### ISSUE TITLE
Presence of _params_ in schema prevents timestamps functionality

### ISSUE THREAD

**Issue by adrian-grajdeanu** [sensedeep/dynamodb-onetable#241]
**Describe the bug**
If ```params``` are specified in the schema, for instance to designate a type field (but even if empty!), then timestamps are no longer created, even if specified in the table.

**Cut/Paste**

test/debug.ts
```
import { inspect } from 'util';
import {AWS, Client, Match, Table, print, dump, delay} from './utils/init'

const Schema = {
  indexes: {
    primary: { hash: "pk" },
  },
  models: {
    User: {
      pk: {
        type: String,
      },
    }
  },
  version: "0.1.0",
  params: { },                                      // <-- This line is the culprit
  format: "onetable:1.0.0"
}

const pk = 'Peter'

const table = new Table({
    name: 'DebugTable',
    client: Client,
    schema: Schema,
    timestamps: true,
    isoDates: true,
    logger: (level, message, context) => {
        // if (level == 'trace' || level == 'data') return
        const contextMessage = context ? `Context: ${inspect(context, false, null)}` : ''
        console.log(`At: ${new Date().toISOString()}\nLevel: ${level}\nMessage: ${message}\n${contextMessage}`)
    }
})

test('Create Table', async() => {
    if (!(await table.exists())) {
        await table.createTable()
        expect(await table.exists()).toBe(true)
    }
})

test('Create with timestamps', async() => {
    const User = table.getModel('User')
    const user: any = await User.create({ pk })
    //  ISO dates 2021-06-30T01:27:19.986Z
    expect(user.created).toBeDefined()
    expect(user.updated).toBeDefined()
})

test('Destroy Table', async() => {
    await table.deleteTable('DeleteTableForever')
    expect(await table.exists()).toBe(false)
})
```

STDOUT
```
Using local Java to run dynamoDB
Spawn DynamoDB 2587
Waiting for 0.0.0.0:4567...
Connected!
DynamoDB is ready
  console.log
    At: 2022-01-06T05:24:10.148Z
    Level: trace
    Message: Loading OneTable

      at Log.logger (test/debug.ts:31:17)

  console.log
    At: 2022-01-06T05:24:10.583Z
    Level: trace
    Message: OneTable createTable for "DebugTable"
    Context: {
      def: {
        AttributeDefinitions: [ { AttributeName: 'pk', AttributeType: 'S' } ],
        KeySchema: [ { AttributeName: 'pk', KeyType: 'HASH' } ],
        TableName: 'DebugTable',
        BillingMode: 'PAY_PER_REQUEST'
      }
    }

      at Log.logger (test/debug.ts:31:17)

  console.log
    At: 2022-01-06T05:24:10.684Z
    Level: trace
    Message: OneTable "put" "User"
    Context: {
      trace: {
        model: 'User',
        cmd: {
          ConditionExpression: 'attribute_not_exists(pk)',
          TableName: 'DebugTable',
          Item: { pk: { S: 'Peter' }, _type: { S: 'User' } },
          ReturnValues: 'NONE'
        },
        op: 'put',
        properties: { pk: 'Peter', _type: 'User' }
      }
    }

      at Log.logger (test/debug.ts:31:17)

  console.log
    At: 2022-01-06T05:24:10.817Z
    Level: data
    Message: OneTable result for "put" "User"
    Context: {
      cmd: {
        ConditionExpression: 'attribute_not_exists(pk)',
        TableName: 'DebugTable',
        Item: { pk: { S: 'Peter' }, _type: { S: 'User' } },
        ReturnValues: 'NONE'
      },
      items: [ { pk: 'Peter' } ],
      op: 'put',
      properties: { pk: 'Peter', _type: 'User' },
      params: { parse: true, high: true, exists: false, checked: true }
    }

      at Log.logger (test/debug.ts:31:17)

  console.log
    At: 2022-01-06T05:24:10.821Z
    Level: trace
    Message: OneTable deleteTable for "DebugTable"

      at Log.logger (test/debug.ts:31:17)
```

STDERR:
```
FAIL test/debug.ts (8.882 s)
  ✓ Create Table (480 ms)
  ✕ Create with timestamps (141 ms)
  ✓ Destroy Table (19 ms)

  ● Create with timestamps

    expect(received).toBeDefined()

    Received: undefined

      44 |     const user: any = await User.create({ pk })
      45 |     //  ISO dates 2021-06-30T01:27:19.986Z
    > 46 |     expect(user.created).toBeDefined()
         |                          ^
      47 |     expect(user.updated).toBeDefined()
      48 | })
      49 |

      at Object.<anonymous> (test/debug.ts:46:26)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        8.951 s, estimated 9 s
Ran all test suites matching /debug.ts/i.
```

**Expected behavior**
Expect ```created``` and ```updated``` fields to be created/updated as specified in the table.

The putItem call should look like so:
```
  console.log
    At: 2022-01-06T05:23:10.841Z
    Level: trace
    Message: OneTable "put" "User"
    Context: {
      trace: {
        model: 'User',
        cmd: {
          ConditionExpression: 'attribute_not_exists(pk)',
          TableName: 'DebugTable',
          Item: {
            pk: { S: 'Peter' },
            _type: { S: 'User' },
            created: { S: '2022-01-06T05:23:10.838Z' },
            updated: { S: '2022-01-06T05:23:10.838Z' }
          },
          ReturnValues: 'NONE'
        },
        op: 'put',
        properties: {
          pk: 'Peter',
          _type: 'User',
          created: '2022-01-06T05:23:10.838Z',
          updated: '2022-01-06T05:23:10.838Z'
        }
      }
    }

      at Log.logger (test/debug.ts:31:17)

```

**Environment (please complete the following information):**
 - OS ```Linux [...] 5.4.0-91-generic #102~18.04.1-Ubuntu SMP Thu Nov 11 14:46:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```
 - Node Version v14.18.2
 - OneTable Version "2.2.2"
 - TypeScript Version "^4.4.0"

**Additional context**
If params are not specified in the schema, functionality is as documented and expected.

**Comment by mobsense** [comment]
The current behavior is for the schema params to overwrite the table params.

We could blend the schema params with the table params. The question is which takes priority?

A wrong param can clearly break the table.

**Comment by adrian-grajdeanu** [comment]
Then the solution to this issue is to change something such that there is only one way to skin the cat, removing ambiguity.

Are there _schema_ parameters and _table_ parameters? If there are, they should be separated, with no way to override/hide each other. Hate to leave js in the dust, but typescript types can help here.

**Comment by adrian-grajdeanu** [comment]
Seems like one can specify the _timestamps_ and _isoDates_ in the schema params. Then they should not be possible to specify in the TableConstructorParams, because schema is already specified there.

**Comment by mobsense** [comment]
The reason for params in the schema is to allow schemas to be persisted in the table so it becomes self-describing.

You can specify any param currently in the Table params or the schema params. They both go through the same Table.setParms API.

The reason schemas take precedence is you can modify the schema at runtime (during development). As the schema is updated, the params are updated too. Not generally something we advise, but in the SenseDeep single-table designer, you need to be able to do this as you develop a schema with the GUI.

We do TS type the Table constructor params. Currently the schema params are not typed (should be typed as OneParams).

Where to go from here. Options:

1. Specify the precedence and blend. i.e. if unset in the schema, preserve the table value.
2. Specify the precedence and overwrite. i.e. if you have schema.params, then it overwrites the table params. If you have no schema, then the table params apply.
3. Partition the params. Some go to the schema (like typeField), some go to the Table.

How to do this without breaking compatibility ... that is the challenge.

**Comment by adrian-grajdeanu** [comment]
With your explanation in mind, I went through the code and see what is going on. I wholeheartedly agree that an entity should be complete and self describing, so no argument about placing params in schema. The qualms I have is with setting the params in table, from a library interface point of view. The actual implementation may differ (keeping prams in Table object) and I understand it came to be so for historical reasons. Now where does the library go from here? When it comes to libraries (highly reusable code), I have a bias toward fixing things 'the right way, even if more painful - provided we have the time'. So I lean towards option 3 above.

Here is what I'd start with:
1. Decide which fields (set A) belong to schema params and should eventually be removed from table params. Mark them deprecated in Table.d.ts
2. Introduce a backward compatibility flag set to true by default (to preserve existing projects); When this is false, change the behavior of Table.setParams to merge schema params into table params; I believe this is what you mean by blending.
3. In Table constructor, before the call to setParams, go through params and for each present field that is in set A (defined in 1. above) give a runtime log about deprecation, and indicate it should be set in schema henceforth. Depending on compatibility flag defined in 2. above, the log entry should mention what is about to happen, so devs understand the why of behavior about to ensue.

Later on when 2.3 (or whatever horizon is decided) comes about
1. remove the compatibility flag
2. remove deprecated fields from TableConstructorParams
2. make the blending behavior the only behavior.

Sometime along the way, fix types of Schema params.

Did I miss anything?

**Comment by mobsense** [comment]
Thank you, that is helpful.

Agree with your approach.  Digging deeper...

Partitioning the fields looks pretty easy. These set of schema params is:

| Property | Type | Description |
| -------- | :--: | ----------- |
| createdField | `string` | Name of the "created" timestamp attribute. Defaults to "created". |
| hidden | `boolean` | Hide templated (value) attributes in Javascript properties. Default true. |
| isoDates | `boolean` | Set to true to store dates as Javascript ISO strings vs epoch numerics. Default false. |
| nulls | `boolean` | Store nulls in database attributes vs remove attributes set to null. Default false. |
| timestamps | `boolean` | Make "created" and "updated" timestamps in items. Default false. |
| typeField | `string` | Name of the "type" attribute. Default "_type". |
| updatedField | `string` | Name of the "updated" timestamp attribute. Default "updated". |

The set of Table params is:

| Property | Type | Description |
| -------- | :--: | ----------- |
| client | `DocumentClient` | An AWS [DocumentClient](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html) instance. |
| crypto | `object` | Optional properties defining a crypto configuration to encrypt properties. |
| logger | `boolean|object` | Set to true to log to the console or set to a logging function(type, message, properties). Type is info|error|trace|exception. Default is false. |
| metrics | `object` | Configure metrics. Default null.|
| name | `string` | The name of your DynamoDB table. |
| schema | `string` | Definition of your DynamoDB indexes and models. |
| senselogs | `object` | Set to a SenseLogs logger instance instead `logger`. Default null. |
| transform | `function` | Callback function to be invoked to format and parse the data before reading and writing. |
| uuid | `string` or function | Create a UUID, ULID or custom ID if the schema model requires and the property is not already defined. Set to `uuid` or `ulid` for the internal UUID or ULID implementations. A ULID is a time-based sortable unique ID. Otherwise set to a function for a custom implementation. If not defined, the internal UUID implementation is used by default when required. |
| validate | `function | Function to validate properties before issuing an API.|
| value | `function | Function to evaluate value templates. Default null. |

It is easy to split Table.setParams into setParams and setSchemaParams. They are internal APIs anyway. The "blending" is probably overstating what is happening. The two params sets define specific properties on the Table object. However, they are 100% disjoint sets in this plan.

In the next minor version upgrade ...  for TypeScript users will catch if anyone supplies the schema params to the Table constructor. For JS users, we can throw an exception. So in both cases, changed behavior is flagged and caught. We may not need a compatibility flag due to this, will need to consider in light of other breaking changes like the UUID change.

For the next patch level release, we can do the deprecation warning you indicate. 

What did you mean by "Sometime along the way, fix types of Schema params."?

**Comment by adrian-grajdeanu** [comment]
Great progress, ty!
What i meant with fixing types for schema params is to narrow down the type of fields from _any_.

Jan 6, 2022 17:53:05 mobsense ***@***.***>:
